import type { ExportDocument } from "./types";

export interface MarkdownExportOptions {
  includeTimestamps?: boolean;
  includeProviderMetadata?: boolean;
}

function section(title: string, body: string): string {
  return `## ${title}\n\n${body.trim()}\n`;
}

function conversationMarkdown(
  document: ExportDocument,
  includeProviderMetadata: boolean,
): string {
  if (document.conversations.length === 0) {
    return "_No conversation content available._\n";
  }

  return document.conversations
    .map((thread) => {
      const model =
        includeProviderMetadata && thread.modelId
          ? ` · Model: \`${thread.modelId}\``
          : "";
      const heading = includeProviderMetadata
        ? `### ${thread.providerName}${model}`
        : `### Conversation`;
      const messages = thread.messages
        .filter((message) => message.role !== "system")
        .map((message) => {
          const label =
            message.role === "user"
              ? "User"
              : includeProviderMetadata
                ? thread.providerName
                : "Assistant";
          return `**${label}**\n\n${message.content.trim()}`;
        })
        .join("\n\n");
      return `${heading}\n\n${messages || "_Empty conversation._"}`;
    })
    .join("\n\n");
}

function reviewMarkdown(document: ExportDocument): string {
  if (document.reviews.length === 0) {
    return "_No AI reviews available._\n";
  }

  return document.reviews
    .map(
      (review) =>
        `### Review of ${review.revieweeName}\n\n` +
        `- **Reviewer:** ${review.reviewerName}\n` +
        `- **Focus:** ${review.focus}\n\n` +
        `${review.text.trim()}`,
    )
    .join("\n\n");
}

function debateMarkdown(document: ExportDocument): string {
  if (!document.debate) {
    return "_No AI debate available._\n";
  }

  const round1 =
    document.debate.critiques.length === 0
      ? "_No critiques._"
      : document.debate.critiques
          .map(
            (entry) =>
              `### ${entry.reviewerName} critiques ${entry.revieweeName}\n\n${entry.text.trim()}`,
          )
          .join("\n\n");

  const round2 =
    document.debate.rebuttals.length === 0
      ? "_No rebuttals._"
      : document.debate.rebuttals
          .map(
            (entry) =>
              `### ${entry.providerName} rebuttal\n\n${entry.text.trim()}`,
          )
          .join("\n\n");

  return `### Round 1 — Critiques\n\n${round1}\n\n### Round 2 — Rebuttals\n\n${round2}`;
}

function recommendationMarkdown(
  document: ExportDocument,
  includeProviderMetadata: boolean,
): string {
  if (!document.recommendation) {
    return "_No final recommendation available._\n";
  }

  const byline = includeProviderMetadata
    ? `**Generated by:** ${document.recommendation.providerName}\n\n`
    : "";

  return `${byline}${document.recommendation.text.trim()}`;
}

/**
 * Canonical Markdown representation of an export. PDF and DOCX build from
 * this string so formatting stays consistent across formats.
 */
export function exportToMarkdown(
  document: ExportDocument,
  options: MarkdownExportOptions = {},
): string {
  const includeTimestamps = options.includeTimestamps ?? true;
  const includeProviderMetadata = options.includeProviderMetadata ?? true;

  const parts: string[] = [`# ${document.title}`, ""];
  parts.push(`- **Project:** ${document.project.name}`);
  if (includeTimestamps) {
    parts.push(`- **Exported:** ${document.exportedAt}`);
  }
  parts.push(`- **Scope:** ${document.scope}`);

  if (document.systemPrompt?.trim()) {
    parts.push("", section("System Prompt", document.systemPrompt));
  }

  switch (document.scope) {
    case "conversation":
      parts.push(
        "",
        section(
          "Conversation",
          conversationMarkdown(document, includeProviderMetadata),
        ),
      );
      break;
    case "recommendation":
      parts.push(
        "",
        section(
          "Final Recommendation",
          recommendationMarkdown(document, includeProviderMetadata),
        ),
      );
      break;
    case "review":
      parts.push("", section("AI Review", reviewMarkdown(document)));
      break;
    case "debate":
      parts.push("", section("AI Debate", debateMarkdown(document)));
      break;
    case "project":
      parts.push(
        "",
        section(
          "Conversation",
          conversationMarkdown(document, includeProviderMetadata),
        ),
      );
      parts.push("", section("AI Review", reviewMarkdown(document)));
      parts.push("", section("AI Debate", debateMarkdown(document)));
      parts.push(
        "",
        section(
          "Final Recommendation",
          recommendationMarkdown(document, includeProviderMetadata),
        ),
      );
      break;
  }

  return `${parts.join("\n").trim()}\n`;
}
